# mysql -u root -p
# grant all on *.* to 'fountain'@'localhost' identified by 'fountain';
# exit

login: &login
  username: fountain
  password: fountain

# Allows username and password to be overridden
<%= file = File.join(Rails.root, "config", "dblogin.yml")
    IO.read(file) if File.exist?(file) %>

common: &common
  adapter: mysql
  database: fountain_development
  host: localhost
  encoding: utf8
  socket: <%= [
    '/opt/local/var/run/mysql5/mysqld.sock',
    '/var/lib/mysql/mysql.sock',
    '/var/run/mysqld/mysqld.sock',
    '/tmp/mysqld.sock',
    '/tmp/mysql.sock',
  ].detect { |socket| File.exist?(socket) } %>
  <<: *login

development:
  <<: *common

test:
  <<: *common
  database: fountain_test

staging:
  <<: *common

production:
  <<: *common

